version: '3.8'

services:
    app:
        container_name: OpenWChat-dev-server
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
            target: development
        env_file:
            - .env
        ports:
            - '8000:8000'
        volumes:
            - ./src:/usr/src/app/src
            - ./tsconfig.json:/usr/src/app/tsconfig.json
        external_links:
            - mongo
        environment:
            - NODE_ENV=development
        command: npm run dev


    prod-app:
        container_name: OpenWChat-prod-server
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        env_file:
            - .env
        ports:
            - '8001:8000'
        volumes:
            - ./src:/usr/src/app/src
            - ./tsconfig.json:/usr/src/app/tsconfig.json
        external_links:
            - mongo
        environment:
            - NODE_ENV=production
        command: npm run start


    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - '27017:27017'